use crate::review::{
    parser::ReviewParseError,
    types::{ReviewAnalysis, ReviewFinding, Severity},
};

pub fn format_review_markdown(analysis: &ReviewAnalysis) -> String {
    let sorted_findings = sorted_findings(&analysis.findings);
    let mut output = String::new();

    output.push_str("# ReviewGate AI Code Review\n\n");
    output.push_str("## Summary\n\n");
    output.push_str(blank_fallback(&analysis.summary, "No summary returned."));
    output.push_str("\n\n");
    output.push_str("## Overall Risk\n\n");
    output.push_str(analysis.overall_risk.display_upper());
    output.push_str("\n\n");
    output.push_str("## Critical\n\n");
    push_severity_section(&mut output, &sorted_findings, &[Severity::Critical]);
    output.push_str("\n## High\n\n");
    push_severity_section(&mut output, &sorted_findings, &[Severity::High]);
    output.push_str("\n## Medium\n\n");
    push_severity_section(&mut output, &sorted_findings, &[Severity::Medium]);
    output.push_str("\n## Low / Notes\n\n");
    push_severity_section(
        &mut output,
        &sorted_findings,
        &[Severity::Low, Severity::Note],
    );
    output.push_str("\n## Test Coverage\n\n");
    output.push_str(
        analysis
            .test_coverage_note
            .as_deref()
            .map(|note| blank_fallback(note, "No specific test coverage note."))
            .unwrap_or("No specific test coverage note."),
    );
    output.push_str("\n\n## Privacy\n\n");
    output.push_str(
        analysis
            .privacy_note
            .as_deref()
            .map(|note| blank_fallback(note, "No specific privacy note."))
            .unwrap_or("No specific privacy note."),
    );
    output.push_str("\n\n[AI generated by ReviewGate]\n");

    output
}

pub fn format_malformed_review_markdown(raw_model_text: &str, error: &ReviewParseError) -> String {
    format!(
        r#"# ReviewGate AI Code Review

## Warning

The model response could not be parsed as structured ReviewGate JSON: {error}

## Raw Model Response

````text
{raw_model_text}
````

[AI generated by ReviewGate]
"#
    )
}

pub fn sorted_findings(findings: &[ReviewFinding]) -> Vec<&ReviewFinding> {
    let mut sorted: Vec<&ReviewFinding> = findings.iter().collect();
    sorted.sort_by(|left, right| {
        left.severity
            .sort_key()
            .cmp(&right.severity.sort_key())
            .then_with(|| left.file_path.cmp(&right.file_path))
            .then_with(|| left.line.cmp(&right.line))
            .then_with(|| left.title.cmp(&right.title))
    });
    sorted
}

fn push_severity_section(
    output: &mut String,
    sorted_findings: &[&ReviewFinding],
    severities: &[Severity],
) {
    let section_findings: Vec<&ReviewFinding> = sorted_findings
        .iter()
        .copied()
        .filter(|finding| severities.contains(&finding.severity))
        .collect();

    if section_findings.is_empty() {
        output.push_str(no_findings_line(severities));
        output.push('\n');
        return;
    }

    for (index, finding) in section_findings.iter().enumerate() {
        if index > 0 {
            output.push('\n');
        }
        push_finding(output, finding);
    }
}

fn push_finding(output: &mut String, finding: &ReviewFinding) {
    output.push_str("### ");
    output.push_str(&finding_heading(finding));
    output.push_str("\n\n");
    output.push_str(blank_fallback(&finding.body, "No details returned."));
    output.push_str("\n\n");
    output.push_str("Category: ");
    output.push_str(finding.category.display_lower());
    output.push_str("\n\n");
    if let Some(suggested_fix) = finding
        .suggested_fix
        .as_deref()
        .map(str::trim)
        .filter(|value| !value.is_empty())
    {
        output.push_str("Suggested fix: ");
        output.push_str(suggested_fix);
        output.push_str("\n\n");
    }
    output.push_str("Confidence: ");
    output.push_str(finding.confidence.display_lower());
    if finding.severity == Severity::Low || finding.severity == Severity::Note {
        output.push_str("\n\nPreview only: low and note findings are not inline-ready in v0.1.");
    }
    output.push('\n');
}

fn finding_heading(finding: &ReviewFinding) -> String {
    let title = blank_fallback(&finding.title, "Untitled finding");
    match (finding.file_path.as_deref(), finding.line) {
        (Some(path), Some(line)) if !path.trim().is_empty() => {
            format!("{}:{} - {}", path.trim(), line, title)
        }
        (Some(path), None) if !path.trim().is_empty() => format!("{} - {}", path.trim(), title),
        _ => title.to_string(),
    }
}

fn no_findings_line(severities: &[Severity]) -> &'static str {
    match severities {
        [Severity::Critical] => "No critical findings.",
        [Severity::High] => "No high findings.",
        [Severity::Medium] => "No medium findings.",
        [Severity::Low, Severity::Note] => "No low or note findings.",
        _ => "No findings.",
    }
}

fn blank_fallback<'a>(value: &'a str, fallback: &'static str) -> &'a str {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        fallback
    } else {
        trimmed
    }
}

#[cfg(test)]
mod tests {
    use super::{format_malformed_review_markdown, format_review_markdown, sorted_findings};
    use crate::review::{
        parser::ReviewParseError,
        types::{Confidence, OverallRisk, ReviewAnalysis, ReviewCategory, ReviewFinding, Severity},
    };

    #[test]
    fn sorts_findings_by_severity_order() {
        let findings = vec![
            finding(Severity::Note, "note"),
            finding(Severity::Medium, "medium"),
            finding(Severity::Critical, "critical"),
            finding(Severity::High, "high"),
            finding(Severity::Low, "low"),
        ];

        let sorted = sorted_findings(&findings);

        assert_eq!(
            sorted
                .iter()
                .map(|finding| finding.severity)
                .collect::<Vec<_>>(),
            vec![
                Severity::Critical,
                Severity::High,
                Severity::Medium,
                Severity::Low,
                Severity::Note
            ]
        );
    }

    #[test]
    fn formats_reviewgate_markdown_by_group() {
        let markdown = format_review_markdown(&ReviewAnalysis {
            summary: "Payment callback risk found.".to_string(),
            findings: vec![ReviewFinding {
                severity: Severity::High,
                category: ReviewCategory::Reliability,
                file_path: Some("src/payment/client.ts".to_string()),
                line: Some(42),
                title: "HTTP request has no timeout".to_string(),
                body: "The new callback call can hang indefinitely.".to_string(),
                suggested_fix: Some("Use a request-scoped timeout.".to_string()),
                confidence: Confidence::High,
                actionable: true,
            }],
            test_coverage_note: Some("No test covers timeout behavior.".to_string()),
            privacy_note: Some("No obvious exposure detected.".to_string()),
            overall_risk: OverallRisk::Medium,
        });

        assert!(markdown.contains("# ReviewGate AI Code Review"));
        assert!(markdown.contains("## Overall Risk\n\nMEDIUM"));
        assert!(markdown.contains("## Critical\n\nNo critical findings."));
        assert!(markdown.contains("### src/payment/client.ts:42 - HTTP request has no timeout"));
        assert!(markdown.contains("Suggested fix: Use a request-scoped timeout."));
        assert!(markdown.contains("Confidence: high"));
    }

    #[test]
    fn malformed_json_fallback_includes_warning_and_raw_text() {
        let markdown =
            format_malformed_review_markdown("plain text output", &ReviewParseError::new("bad"));

        assert!(markdown.contains("could not be parsed"));
        assert!(markdown.contains("plain text output"));
    }

    fn finding(severity: Severity, title: &str) -> ReviewFinding {
        ReviewFinding {
            severity,
            category: ReviewCategory::Correctness,
            file_path: None,
            line: None,
            title: title.to_string(),
            body: title.to_string(),
            suggested_fix: None,
            confidence: Confidence::Medium,
            actionable: true,
        }
    }
}
