pub fn format_review_markdown(model_output: &str) -> String {
    let trimmed = model_output.trim();
    format!(
        r#"# ReviewGate Review

## Summary

{summary}

## Critical / High / Medium findings

{findings}

## Low / Notes summary only

Low-severity and note-level feedback is summary-only in v0.1 to keep the review focused.

## Test coverage note

Check whether behavior changes in this MR are covered by relevant tests.

## Privacy note

Diff text was redacted for common secret patterns before model review.

[AI generated by ReviewGate]
"#,
        summary = if trimmed.is_empty() {
            "No model output was returned."
        } else {
            trimmed
        },
        findings = if trimmed.is_empty() {
            "No findings were returned by the model."
        } else {
            trimmed
        }
    )
}
